version: '3'

services:

  goapi:
    image: iamdeowanshi/goapi
    container_name: "goapi"
    networks:
      - webnet
    ports:
      - 3000:3000
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: "redis"
    networks:
      - webnet

networks:
  webnet: